# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrument_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instruments',
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'operators',
            },
        ),
        migrations.CreateModel(
            name='PositionStatsPerTile',
            fields=[
                ('rsltp_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('cum_a', models.BigIntegerField()),
                ('cum_c', models.BigIntegerField()),
                ('cum_t', models.BigIntegerField()),
                ('cum_g', models.BigIntegerField()),
                ('cum_n', models.BigIntegerField()),
                ('cum_aq', models.BigIntegerField()),
                ('cum_cq', models.BigIntegerField()),
                ('cum_tq', models.BigIntegerField()),
                ('cum_gq', models.BigIntegerField()),
                ('cum_nq', models.BigIntegerField()),
                ('cum_amee', models.FloatField(default=0)),
                ('cum_cmee', models.FloatField(default=0)),
                ('cum_tmee', models.FloatField(default=0)),
                ('cum_gmee', models.FloatField(default=0)),
                ('cum_nmee', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'position_stats_per_tile',
            },
        ),
        migrations.CreateModel(
            name='PrincipalInvestigators',
            fields=[
                ('pi_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'principal_investigators',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mihiseqaApp.PrincipalInvestigators')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ReadStatsPerTile',
            fields=[
                ('rslt_id', models.AutoField(primary_key=True, serialize=False)),
                ('tile', models.PositiveSmallIntegerField()),
                ('read12', models.PositiveSmallIntegerField(choices=[(1, 'read1'), (2, 'read2')], default=1)),
                ('cum_a', models.BigIntegerField()),
                ('cum_c', models.BigIntegerField()),
                ('cum_t', models.BigIntegerField()),
                ('cum_g', models.BigIntegerField()),
                ('cum_n', models.BigIntegerField()),
                ('cum_arq', models.FloatField()),
                ('cum_mee', models.FloatField()),
                ('nreads', models.BigIntegerField()),
                ('nbases', models.BigIntegerField()),
            ],
            options={
                'db_table': 'read_stats_per_tile',
            },
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('flowcell_id', models.CharField(max_length=10, unique=True)),
                ('rundate', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mihiseqaApp.Instruments')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mihiseqaApp.Operators')),
            ],
            options={
                'db_table': 'runs',
            },
        ),
        migrations.CreateModel(
            name='SampleSheet',
            fields=[
                ('rsl_id', models.AutoField(primary_key=True, serialize=False)),
                ('lane', models.IntegerField()),
                ('sample', models.CharField(max_length=20)),
                ('index1', models.CharField(max_length=15)),
                ('index2', models.CharField(blank=True, max_length=15, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mihiseqaApp.Projects')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mihiseqaApp.Runs')),
            ],
            options={
                'db_table': 'sample_sheet',
            },
        ),
        migrations.AddField(
            model_name='readstatspertile',
            name='rsl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mihiseqaApp.SampleSheet'),
        ),
        migrations.AddField(
            model_name='positionstatspertile',
            name='rslt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mihiseqaApp.ReadStatsPerTile'),
        ),
        migrations.AlterUniqueTogether(
            name='samplesheet',
            unique_together=set([('run_id', 'project', 'sample', 'index1')]),
        ),
    ]
