# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mihiseqaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplesheet',
            old_name='run_id',
            new_name='run',
        ),
        migrations.AlterUniqueTogether(
            name='samplesheet',
            unique_together=set([('run', 'project', 'sample', 'index1')]),
        ),
    ]
